### ISSUE TITLE
[Bug] `con.rs` file prevents the repo from being cloned/used on windows

### ISSUE THREAD

**Issue by kpalang** [kayyagari/catapult#3]
As mentioned by a user on Slack, the `src-tauri/src/con.rs` file prevents the repository from being cloned or opened on windows. An explanation can be found [here](https://mirthconnect.slack.com/archives/C05FV9Y5RE2/p1688753527964059).

**Comment by jonbartels** [comment]
"a user" was meeeeeeeeeee

**Comment by kayyagari** [comment]
I didn't know that Jon's post on Slack regarding "creating files with name `CON` on Windows" was related to this. Is this still an issue on Windows?. If yes, will rename the file to `connection.rs`.

**Comment by kpalang** [comment]
Yes, the issue is still there. I actually filed the report when trying to clone the repo on a Windows machine.
